# Generated by Django 5.1.4 on 2026-05-12 18:29

import django.core.validators
import django.db.models.deletion
import learning.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('points', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/enseignants/', validators=[learning.validators.validate_file_size])),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/etudiants/', validators=[learning.validators.validate_file_size])),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/')),
                ('est_publie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_cours', max_length=20)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='learning.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='learning.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='learning.module')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='learning.module')),
            ],
            options={
                'verbose_name_plural': 'Cours',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='learning.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='learning.module')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.module')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('info', 'Information'), ('note', 'Nouvelle note'), ('cours', 'Nouveau cours'), ('quiz', 'Nouveau quiz'), ('reclamation', 'Réclamation mise à jour'), ('certificat', 'Certificat obtenu')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('est_lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_termine', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='learning.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='learning.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='learning.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('note_de_passage', models.PositiveIntegerField(default=70)),
                ('est_publie', models.BooleanField(default=False)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.module')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz'),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolue', 'Résolue')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='learning.etudiant')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='learning.module')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_ressource', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'Document PDF'), ('link', 'Lien externe')], max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cours/ressources/', validators=[learning.validators.validate_file_size])),
                ('url', models.URLField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='learning.cours')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('reussi', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='learning.etudiant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='learning.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='learning.soumissionquiz')),
            ],
        ),
        migrations.AddIndex(
            model_name='enseignant',
            index=models.Index(fields=['user'], name='enseignant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['user'], name='etudiant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['etudiant', 'module'], name='inscr_etud_mod_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'module')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'est_lu'], name='notif_dest_lu_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progression',
            unique_together={('etudiant', 'cours')},
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['statut'], name='reclam_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['-date_creation'], name='reclam_date_idx'),
        ),
    ]
