# Generated by Django 5.1.4 on 2026-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
